name: Grains
main: si.zbe.grains.Main
author: TheZbe
description: 'Minecraft improved.'
api-version: 1.13
version: ${project.version}
depend: [ProtocolLib]
commands:
  gworkbench:
    description: 'Gives player a portable workbench.'
    usage: /<command>
    aliases: gwb
  genderchest:
    description: 'Gives player a portable ender chest.'
    usage: /<command>
    aliases: gec
  grains:
    description: 'Grains admin commands.'
    usage: /<command>
    aliases: grs
permissions:
  grains.*:
    description: 'Control the grain.'
    default: op
    children:
      grains.admin: true
      grains.crops: true
      grains.compass: true
      grains.armor: true
      grains.workbench: true
      grains.enderchest: true
  grains.admin:
    description: 'Grains admin commands.'
    default: op
  grains.crops:
    description: 'Harvests crops on right click.'
    default: true
  grains.compass:
    description: 'Player recieves death compass on respawn.'
    default: op
  grains.armor:
    description: 'Replaces armor on right-click.'
    default: true
  grains.workbench:
    description: 'Gives player a portable workbench.'
    default: op
  grains.enderchest:
    description: 'Gives player a portable enderchest.'
    default: op


